### ISSUE TITLE
Textual statuscode, but integer is expected

### ISSUE THREAD

**Issue by juukie** [spatie/laravel-link-checker#10]
Hey @freekmurze,

Using version 2.0 I crawled a link with an unresponsive host. The `BaseReporter` will assign it the statuscode `Host did not respond` in the `hasBeenCrawled` method:
```
$statusCode = $response ? $response->getStatusCode() : static::UNRESPONSIVE_HOST;
```

This exception will be thrown:

```
Type error: Argument 1 passed to Spatie\LinkChecker\Reporters\BaseReporter::isSuccessOrRedirect() must be of the type integer, string given, called in /var/www/vhosts/keizeryachts.com/httpdocs/vendor/s
  patie/laravel-link-checker/src/Reporters/LogBrokenLinks.php on line 36
```

I guess `const UNRESPONSIVE_HOST = 'Host did not respond';` should be changed to a http status code?

**Comment by freekmurze** [comment]
Hi,

could you try the `dev-master` version and let me know if that fixes this issue for you?

**Comment by juukie** [comment]
Ah I see it has been fixed but it's unreleased.
https://github.com/spatie/laravel-link-checker/commit/2c2969f8cda02715f069836289aa0dd058bbdb8e
This will fix indeed! 👍 Thanks

**Comment by freekmurze** [comment]
The fix is now tagged. Upgrading to `1.0.3` fixes the problem.
