### ISSUE TITLE
Disarranged version numbers

### ISSUE THREAD

**Issue by arubacao** [spatie/laravel-link-checker#19]
It doesn't seem like this is intended:
![wrongversionnumbers](https://user-images.githubusercontent.com/7462542/30888289-05f733a0-a320-11e7-92b3-81dac53f7af3.PNG)

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. Seems like we messed up the releases big time. Apologies for that.

I've tagged a new version 2.1.0 that contains the latest and greatest version of this package. I've also tagged version 1.2.0 which is basically a rerelease of 1.0.1 so everything in the major 1 version stays compatible.
