### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by faralimite** [spatie/laravel-link-checker#2]
composer require spatie/laravel-link-checker
Using version ^1.0 for spatie/laravel-link-checker
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-link-checker 1.0.0 requires spatie/crawler ^1.1.1 -> satisf
iable by spatie/crawler[1.1.1].
    - Installation request for spatie/laravel-link-checker ^1.0 -> satisfiable b
y spatie/laravel-link-checker[1.0.0].
    - Conclusion: remove guzzlehttp/guzzle 5.3.0
    - Conclusion: don't install guzzlehttp/guzzle 5.3.0
    - spatie/crawler 1.1.1 requires guzzlehttp/guzzle ^6.1 -> satisfiable by guz
zlehttp/guzzle[6.1.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.0].
    - Installation request for guzzlehttp/guzzle == 5.3.0.0 -> satisfiable by gu
zzlehttp/guzzle[5.3.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Could you try explicitly requiring Guzzle 6.1 before installing this package?

```json
    "guzzlehttp/guzzle": "^6.1",
```
