### ISSUE TITLE
Ignore href:tel

### ISSUE THREAD

**Issue by piep14** [spatie/laravel-link-checker#3]
Hello,

Very good tool. By cons , he mistake me spring type connections "tel: " .

Possible to ignore them?

Thank you

**Comment by sebastiandedeyne** [comment]
Makes sense! I'll look into it sometime soon. Moving this issue to the spatie/crawler repository. Feel free to send a PR if you're up for it.

**Comment by sebastiandedeyne** [comment]
Just tagged v1.3.1 of spatie/crawler which resolves the issue. Running a composer update should do the trick!
