### ISSUE TITLE
How to set crawl queue?

### ISSUE THREAD

**Issue by Tropicalista** [spatie/laravel-link-checker#33]
On your crawler package you say: 

> When a site is very large you may want to store that queue elsewhere, maybe a database. In such cases you can write your own crawl queue.

On this laravel package instead there is no possibility to set "setCrawlQueue". So my question is: if I try to crawl a very huge site, about 100000 pages, does this script run out of memory?

**Comment by freekmurze** [comment]
It depends a bit on how the site is structured and how many memory you allocate to php. Try to use the default configuration first and monitor memory usage a bit.
