### ISSUE TITLE
 Cannot access private property

### ISSUE THREAD

**Issue by muShubbar** [spatie/laravel-link-checker#37]
**When running the link-checker:run ** 

php artisan link-checker:run

In 21b75f75bd145c6f34958d7d351ee08f51fd860e.php line 11:

  Cannot access private property GuzzleHttp\Psr7\Uri::$scheme (View: D:\xampp\htdocs\projects\mustafa.test\vendor\spatie\laravel-link-checker\resources\views\crawlRe
  port.blade.php)

In 21b75f75bd145c6f34958d7d351ee08f51fd860e.php line 11:

  Cannot access private property GuzzleHttp\Psr7\Uri::$scheme

-----

**My composer.json** 

    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~4.0",
        "google/recaptcha": "~1.1",
        "guzzlehttp/guzzle": "^6.3",
        "intervention/image": "^2.4",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4.0",
        "mews/purifier": "^2.0",
        "spatie/laravel-link-checker": "^3.0"
    },

**Comment by VincentVanWijk** [comment]
if anyone is encountering this error, you can fix it by changing the link inside the foreach of crawlReport.blade.php 

**FROM:**
<a href="{{ $url->scheme.'://'.$url->host.''.$url->path }}">
                    {{ $url->host.''.$url->path }}
 </a>

**TO:**
<a href="{{ $url->getScheme().'://'.$url->getHost().''.$url->getPath() }}">
                    {{ $url->getHost().''.$url->getPath() }}
 </a>
